apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-cart-backend
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-cart-backend
  newTag: v1.0.1
- name: cart
  newName: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/cart
  newTag: d27a640bb3837def1c62133009f899615d2648a2
namespace: e-commerce
resources:
- ../../../base/cart
