apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cart-service.yaml
  - cart-configmap.yaml
  - cart-deployment.yaml
images:
- name: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/cart
  newName: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/cart
  newTag: v1.0.1