---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: users
        image: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/users:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: users-postgre
        - configMapRef:
            name: users-postgre