apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - store-ui-service.yaml
  - store-ui-ingress.yaml
  - store-ui-deployment.yaml
images:
- name: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/store-ui
  newName: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/store-ui
  newTag: v1.0.1