apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - product-service.yaml
  - product-configmap.yaml
  - product-secret.yaml
  - product-deployment.yaml
images:
- name: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/products
  newName: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/products
  newTag: v1.0.1